# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g yarn
    - run: ip r
    - run: sudo ufw allow 3000
    - run: |
        cd live-server
        npm install
        yarn add gh-pages
        yarn run deploy
    
    - name: Get Server Files
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Live Server
        path: |
          live-server/
          !live-server/node_modules/
